---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limmx/webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      name: webapp
      labels:
        app: webapp

    spec:
      containers:
      - name: webapp
        image: limmx/webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    app: webapp

  type: NodePort
  ports:
  - nodePort: 8888
    port: 8888
    targetPort: 8888

