apiVersion: apps/v1
kind: Service
metadata:
  labels:
    k8s-app: webapp
  name: webapp-services
  namespace: default
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    k8s-app: webapp
  type: NodePort

